#!/bin/bash
# FPV Copilot Sky - Unified Sudoers Configuration
# Creates a single, hardened sudoers file with minimal required permissions.
#
# Run this script with: sudo bash scripts/setup-sudoers.sh
#
# This replaces the previous split files:
#   /etc/sudoers.d/tailscale
#   /etc/sudoers.d/fpvcopilot-wifi
#   /etc/sudoers.d/fpvcopilot-system
#
# Security principles:
#   - Single file: /etc/sudoers.d/fpvcopilot-sky
#   - Fixed user: fpvcopilotsky (never $USER or $SUDO_USER)
#   - All wildcards restricted to the minimum needed by the codebase
#   - No shell=True, no unrestricted tee/mkdir/sysctl

set -e

SUDOERS_FILE="/etc/sudoers.d/fpvcopilot-sky"
FPVCOPILOT_USER="fpvcopilotsky"

echo "🔐 FPV Copilot Sky - Setting up sudoers for user: $FPVCOPILOT_USER"

# Remove legacy sudoers files if they exist
for OLD_FILE in /etc/sudoers.d/tailscale /etc/sudoers.d/fpvcopilot-tailscale /etc/sudoers.d/fpvcopilot-wifi /etc/sudoers.d/fpvcopilot-system; do
    if [ -f "$OLD_FILE" ]; then
        echo "  🗑️  Removing legacy sudoers file: $OLD_FILE"
        rm -f "$OLD_FILE"
    fi
done

# Create unified sudoers file
cat > "$SUDOERS_FILE" << 'SUDOERS_EOF'
# =============================================================================
# FPV Copilot Sky - Unified Sudoers Configuration
# =============================================================================
# Auto-generated by scripts/setup-sudoers.sh
# All permissions for the fpvcopilotsky service user in one place.
# Each entry is restricted to the minimum wildcard scope needed.
# =============================================================================

# --- Service management (system_service.py) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart fpvcopilot-sky
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl start fpvcopilot-sky
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop fpvcopilot-sky
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl status fpvcopilot-sky
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart nginx
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl status nginx
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl reload nginx
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/journalctl -u fpvcopilot-sky *

# --- Tailscale VPN (vpn_provider.py) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/tailscale up
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/tailscale up *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/tailscale down
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/tailscale logout
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/tailscale status
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/tailscale status *

# --- WiFi scanning (wifi.py) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/iw dev * scan
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/iw dev * scan *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/iw dev * link

# --- NetworkManager WiFi (wifi.py) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/nmcli device wifi connect *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/nmcli device wifi disconnect
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/nmcli device wifi rescan
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/nmcli dev wifi rescan
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/nmcli connection up *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/nmcli connection down *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/nmcli connection show
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/nmcli connection show *

# --- IP routing (wifi.py, vpn_interface.py, network_optimizer.py) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip route add *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip route del *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip route change *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip route replace *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip route show
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip route show *

# --- IP link management (wifi.py, modem_interface.py, ethernet.py, network_optimizer.py) ---
# Used for: up/down, mtu, txqueuelen — wildcard needed for dynamic interface names
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip link set *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip link show
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip link show *

# --- IP address queries (gstreamer_service.py, vpn_interface.py) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip addr show
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip -o addr show
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip -o -4 addr show

# --- Traffic control / CAKE (network_optimizer.py) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/tc qdisc *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/tc -s qdisc *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/tc class *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/tc filter *

# --- iptables mangle (network_optimizer.py — DSCP marking for VPN policy routing) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/iptables -t mangle *
# --- iptables-save / iptables-restore (policy_routing_manager.py — batch rule management) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/iptables-save
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/iptables-save -t mangle
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/iptables-restore
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/iptables-restore --noflush
# --- WireGuard status (vpn_health_checker.py — VPN peer detection & health monitoring) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/wg show all
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/wg show all *

# --- ping (latency_monitor.py — fallback when cap_net_raw not set on binary) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/ping

# --- Policy routing rules (policy_routing_manager.py, network_optimizer.py) ---
# Batch mode: a single call replaces 6 individual ip rule del/add sudo calls
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip -force -batch *
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip rule *

# --- MPTCP (mptcp.py) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ip mptcp *

# --- Sysctl — RESTRICTED to specific network parameters (network_optimizer.py) ---
# Instead of the dangerous "sysctl -w *", each allowed parameter is listed explicitly.
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/sysctl -w net.ipv4.tcp_congestion_control=*
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/sysctl -w net.core.rmem_max=*
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/sysctl -w net.core.wmem_max=*
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/sysctl -w net.ipv4.tcp_window_scaling=*
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/sysctl -w net.ipv4.tcp_timestamps=*
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/sysctl -w net.ipv4.tcp_rto_min=*
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/sysctl -w net.mptcp.enabled=*

# --- Ethtool — RESTRICTED to disabling Wake-on-LAN (network_optimizer.py:298) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/sbin/ethtool -s * wol d

# --- DNS cache / dnsmasq (dns_cache.py) ---
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/apt-get update
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/apt-get install -y dnsmasq
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl start dnsmasq
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop dnsmasq
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl status dnsmasq
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart dnsmasq
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/systemctl enable dnsmasq
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/killall -USR1 dnsmasq
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/killall -HUP dnsmasq

# --- File operations — RESTRICTED to specific paths (dns_cache.py, policy_routing_manager.py) ---
# Instead of "tee *" (any file) and "mkdir -p *" (any directory):
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/tee /etc/dnsmasq.d/fpvcopilot.conf
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/tee /etc/resolv.conf
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/tee /etc/iproute2/rt_tables
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/tee -a /etc/iproute2/rt_tables
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/mkdir -p /etc/dnsmasq.d
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/cp /etc/resolv.conf /etc/resolv.conf.backup
fpvcopilotsky ALL=(ALL) NOPASSWD: /usr/bin/cp /etc/resolv.conf.backup /etc/resolv.conf
SUDOERS_EOF

# Set proper permissions
chmod 440 "$SUDOERS_FILE"

# Verify syntax
if visudo -c -f "$SUDOERS_FILE" > /dev/null 2>&1; then
    echo "  ✅ Unified sudoers file created: $SUDOERS_FILE"

    # --- ping capability ---
    # ping needs cap_net_raw to create ICMP raw sockets as non-root.
    # Most distros ship ping with setuid or this capability; this board does not.
    # We set it here so the latency monitor works without sudo prefix.
    # setcap survives reboots but is lost when iputils-ping is upgraded.
    # The sudoers entry above (sudo ping) acts as a drop-in fallback.
    PING_BIN="$(command -v ping 2>/dev/null || echo /usr/bin/ping)"
    if [ -x "$PING_BIN" ]; then
        if setcap cap_net_raw+ep "$PING_BIN" 2>/dev/null; then
            echo "  ✅ cap_net_raw granted to $PING_BIN (non-root ping enabled)"
        else
            echo "  ⚠️  setcap failed — sudo ping fallback will be used (check libcap2-bin is installed)"
        fi
    fi
    echo ""
    echo "  Permissions configured:"
    echo "    - Service management (fpvcopilot-sky, nginx)"
    echo "    - Tailscale VPN management"
    echo "    - WiFi scanning and connection management"
    echo "    - IP routing, link, and address management"
    echo "    - Traffic control (CAKE bufferbloat)"
    echo "    - iptables mangle (VPN policy routing)"
    echo "    - MPTCP management"
    echo "    - Sysctl (restricted to 7 specific network parameters)"
    echo "    - Ethtool (restricted to WoL disable)"
    echo "    - DNS cache (dnsmasq config, restricted file paths)"
    echo "    - Policy routing (iptables mangle + ip rule + rt_tables)"
    echo ""
    echo "  Removed dangerous wildcards:"
    echo "    ❌ tee *          → ✅ tee /etc/dnsmasq.d/fpvcopilot.conf, tee /etc/resolv.conf"
    echo "    ❌ sysctl -w *    → ✅ sysctl -w net.ipv4.tcp_congestion_control=*, etc."
    echo "    ❌ mkdir -p *     → ✅ mkdir -p /etc/dnsmasq.d"
    echo "    ❌ ethtool -s *   → ✅ ethtool -s * wol d"
    echo "    ❌ nmcli modify * → removed (unused by code)"
    echo "    ❌ nmcli dev set  → removed (unused by code)"
else
    echo "  ❌ Error: Invalid sudoers syntax!"
    rm -f "$SUDOERS_FILE"
    exit 1
fi
